import React from 'react'
import './About.css'

function About() {
  return (
    <div className="q"><p><h1>DO YOU KNOW WHO AM I?....</h1><h2> HEYYY EVERYONE....</h2>
     IAM FARSANA ABDUL LATHEEF FROM KERALA,INDIA.
    IAM CURRENTLY PERFORMING AN INTERSHIP IN SOFTCRONICS.
    I HAVE RECENTLY COMPLETED MY DEGREE FROM EMEA ARTS AND SCIENCE COLLAGE KONDOTTY IN ENGLISH LANGUAGE AND LITERATUFRE.
    I TOOK A 6 MONTHS BREAK FROM MY ACADEMIC STREAM TO MAKE A SELF STUDY ABOUT MY IT MIND AND THIS LEAD ME TO BE A IT PROFFESIONAL.</p>
       
    </div>
  )
}

export default About